name: joke_flutter_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  # network handling
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0

  # json handling
  json_annotation: ^4.9.0 
  equatable: ^2.0.7

  # state handling
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1

  # assets gen 
  flutter_gen: ^5.9.0

  # toast
  fluttertoast: ^8.2.11

  # ui helper
  delayed_widget: ^1.1.2
  just_audio: ^0.9.46 # for audio

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # code generation
  build_runner: ^2.4.14
  flutter_gen_runner: ^5.8.0
  json_serializable: ^6.9.3

  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_gen:
  output: lib/core/gen/
  line_length: 80 

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/audio/
  
  fonts: 
    - family: BRFirmaFontFamily
      fonts:
        - asset: assets/fonts/BRFirmaFontFamily/BRFirmaBlack.otf
        - asset: assets/fonts/BRFirmaFontFamily/BRFirmaRegular.otf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
